

###
# General Settings
###

# Whether verbose logging is enabled or not. (default = false)
verbose: false
language: en-US

###
# Database
###
database:
  type: sqlite
  host: localhost:3306
  database: asmp
  auth:
    user: username
    password: password

###
# Placeholder API
###
placeholderAPI:
  enabled: false

modules:
  removeXPOnDeath:
    enabled: true
  removeInventoryOnDeath:
    enabled: true
  leveling:
    enabled: true
  bedhealing:
    enabled: true
  biome-titles:
    enabled: true


###
# Metrics & update checker
###
metrics: true
update_check: true