

###
# General Settings
###

# Whether verbose logging is enabled or not. (default = false)
verbose: false
language: en-US


###
# Placeholder API
###
placeholderAPI:
  enabled: false

modules:
  removeXPOnDeath:
    enabled: true
  removeInventoryOnDeath:
    enabled: true
  leveling:
    enabled: true
  bedhealing:
    enabled: true


###
# Metrics & update checker
###
metrics: true
update_check: true